#!/usr/bin/env python3
"""Generate the conservative provider/source baseline; never infer verification.

This baseline is replaced by evidence-backed classifications during #11/#20.
--check detects a stale inventory when providers or declared source modes change.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def render() -> str:
    manifests = []
    for path in sorted((ROOT / "plugins").glob("*/plugin.json")):
        manifest = json.loads(path.read_text(encoding="utf-8"))
        assert manifest["id"] == path.parent.name, path
        modes = manifest.get("supportedModes", [])
        assert modes and len(modes) == len(set(modes)), path
        manifests.append((path, manifest))
    lines = [
        "# Provider compatibility baseline", "",
        "Generated by `python tools/portability/provider_inventory.py`; validate with `--check`.", "",
        "This is a source inventory, not a claim of credentialed compatibility. Each row",
        "expands a manifest's declared mode; `auto` selects the listed default mode.",
        "Actual credential acquisition (files, OS stores, environment, browser import)",
        "must still be audited per provider in [#11](https://github.com/Hashim-K/usagestat/issues/11).",
        "No entry is verified by a mocked response or a successful build.", "",
        "States: **I** = implemented but unverified; **B3** = blocked on native",
        "build/runtime qualification in [#3](https://github.com/Hashim-K/usagestat/issues/3).",
        "B3 is a minimum prerequisite, not an assertion that compilation is the only gap.",
        "Future **V** entries require dated OS/version/auth evidence; **U** entries require",
        "an upstream unsupported reason and a supported alternative where available.", "",
        "Additional completion gates by method: local/CLI helper execution #5 and path",
        "fixtures #11; Windows credential-store reads #10; IDE process discovery #12;",
        "macOS automatic browser import #18; Windows supported browser authentication #19.",
        "Explicit configured API keys/cookies and automatic import are separate methods.",
        "Manifest modes do not imply every method is available on every platform.", "",
        f"Inventory: {len(manifests)} providers; {sum(len(m['supportedModes']) for _, m in manifests)} declared provider/source pairs.", "",
        "| Provider | Source | Auto selects | Linux | macOS | Windows |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for path, manifest in manifests:
        for mode in manifest["supportedModes"]:
            lines.append(f"| [{manifest['id']}](../{path.relative_to(ROOT).as_posix()}) | {mode} | {manifest.get('autoMode', 'auto')} | I | B3 | B3 |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/provider-compatibility.md"
    result = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != result:
            raise SystemExit("Provider inventory is stale; run tools/portability/provider_inventory.py")
        print("Provider inventory covers all current manifests and declared source modes.")
    else:
        path.write_text(result, encoding="utf-8")
        print(path)
